### ISSUE TITLE
Conflicts in objectives between manuscript and database improvement

### ISSUE THREAD

**Issue by BruceKendall** [BruceKendall/MPM-errors#1]
For the manuscript, the goal of classifying the COM[P]ADRE models is document the frequency of errors in published MPMs. For the databases, the goal of this review is to improve the quality of the models in the database by fixing errors in the published models.

These goals are broadly aligned, but there are a couple of places where we might ask the Compadrinos to do different things depending on the goal.

1. When a value cannot be determined from the published source, RSG suggests contacting the authors. This would get a definitive answer for the purpose of correcting the model; but for the manuscript it would be sufficient (and useful) to record that the model description was unclear. 
2. For the manuscript, the unit of observation is the study or publication, as we are documenting the practices of scientists. Also all models within the study are likely to have been constructed in similar ways. However, correcting the models in the database requires that each model within a study be documented.

**Decision needed:** Do we prioritize the manuscript or the database?

**Comment by BruceKendall** [comment]
My personal preference is to prioritize the manuscript, for several reasons:
1. For both issues, the manuscript-focus requires less work and can be completed faster.
2. For both issues, it is straightforward to make a second pass to fill in additional material needed for database correction
3. For the first issue, consultation with the author, unless carefully documented, obscures the fact that the published model description was unclear. This prevents a secondary goal of the manuscript, of highlighting problems associated with inadequate documentation.

**Comment by robcito** [comment]
Hi agree with the priority on the ms - this will in turn help streamline the deployment of the suggestions that are made in the ms across both COMPADRE & COMADRE, even if the ms focuses on a subset of COMADRE only
