### ISSUE TITLE
Examples needed: Census type

### ISSUE THREAD

**Issue by BruceKendall** [BruceKendall/MPM-errors#4]
We need examples illustrating how to select the census type. Ideally we will have one or more for each of:
- Pre
- Post
- Post+
- Mid
- Flow
- Ambiguous

**Comment by BruceKendall** [comment]
We now have examples for Pre, Post, Post+, and Flow.

**Comment by robcito** [comment]
I'd suggest to leave options Mid and Ambiguous without examples and fill them in once/if the compadrinos report examples that would be pertinent to either of them
