### ISSUE TITLE
How should we code "not applicable"?

### ISSUE THREAD

**Issue by BruceKendall** [BruceKendall/MPM-errors#6]
Rob has suggested writing "NA" in various places for "not applicable". The problem is, when R imports the data file, blanks will *also* be coded "NA", and we will be unable to distinguish entries that were directly assessed from those that were just left blank. This means that future updates will have to revisit these cases, in case they had been overlooked rather than actively assessed. This is particularly problematic if we do not do a comprehensive scan of the database.

I had proposed using "na" (lowercase) as the sign that the field had been assessed. However, it is awfully easy to forget; and between Excel's autofill and a likelihood that someone will rectify capitalization before finalizing the file, it is likely that some or all of them will turn into "NA" anyway. So we need something more distinct, at least as far away as "N/A", but perhaps even more distant.

**Decision needed:** How should we code "not applicable"?

**Comment by robcito** [comment]
I think it makes sense to go with "not applicable" too

**Comment by BruceKendall** [comment]
OK, we'll go with "Not Applicable"
