### ISSUE TITLE
Looking for appropriate treatment of continuous breeders

### ISSUE THREAD

**Issue by BruceKendall** [BruceKendall/MPM-errors#7]
Right now, the `CensusType` variable refers to the *model* -- this is appropriate and needed, so that we can do subsequent analyses on the model. But there is a separate question of whether the model is appropriate to the species' life history. For seasonal breeders, any birth-pulse model is appropriate. But thinking through the lionfish paper, I realized that, while the species itself is a continuous breeder, they do not apply a birth-flow formulation, instead relying on a short timestep (1 month) to do the work for them.

So would it be possible for the compadrinos to assess the actual breeding schedule from the description of the life history? The possibilities I can think of are:
1. Pulsed
2. Continuous and constant
3. Continuous but cyclically varying

For 1 and 3 we would also need to know the length of the cyclical variation (a year? 28 days? 24 hours?) or time between pulses, to compare with the timestep of the model.

In some sense, this gets beyond the original scope of the paper (although it is a potential source of inaccurate inference), and would require a theoretical treatment of birth-flow models that is probably more than I want to get into (is the treatment in Caswell the most general version out there?).

**Decision needed**: do we ask the compdrinos to assess actual breeding strategy?

**Comment by robcito** [comment]
I think it'd be OK to ask them to peruse through the train-set of pubs if they can see that info (my guess is that pop ecologists do a terrible job at describing their model species' life cycle). I feel a bit worry about sending them to the inter webs to fill in the missing info, bc I suspect some of these traits may be quite environmentally labile anyways. What do you think?

**Comment by BruceKendall** [comment]
I agree that any classification here should be based on the life history of the population under study. In the case of the lionfish paper it was fairly clear: the females are described as releasing egg masses about every 3 days on average, the model timestep was a month, the maternity was calculated by summing up the egg masses over the month (neglecting the fact that some adults might die before the end of the month, and then they proceeded to construct a birth-pulse model (incorrectly, as it turns out).

For the present time, maybe we can just ask them to say something in the notes if they notice a discrepancy between the way reproduction is treated in the model and how it is described in the life history.

Morris, James A., Kyle W. Shertzer, and James A. Rice. 2010. “A Stage-Based Matrix Population Model of Invasive Lionfish with Implications for Control.” Biological Invasions 13 (1). Springer Nature: 7–12. doi:10.1007/s10530-010-9786-8.

**Comment by robcito** [comment]
I agree - what you propose above is sensible and certainly something that the compadrinos can do

**Comment by BruceKendall** [comment]
I've added a comment to this effect in the section on **CensusType**
