### ISSUE TITLE
Coping with non-ascii characters when exporting from com[p]adre

### ISSUE THREAD

**Issue by BruceKendall** [BruceKendall/MPM-errors#8]
In the early days of this project I used `write.csv()` to export a subset of the database and then read the csv file into Excel to add additional columns. Somewhere along the way I discovered that the database had non-ascii characters (accents, superscripts, etc.) and that these had gotten lost. I don't know whether the loss was in `write.csv()` or reading into Excel.

It's probably possible to preserve these on write by using an encoding option in write.table(). But I don't know if Excel will recognize these in a csv file. Perhaps a better way is to write directly to Excel (e.g., with the **xlsx** package); or use something other than Excel as a data input system (although since Rob already set up an Excel template that may be the default mode for the compadrinos).

**Comment by robcito** [comment]
Saving/reading as/from write.csv with the proper UTF option would do the trick, but yeah, we can just have the compadrinos for the time being work on an .xlsx file and then we read it with the xlsx library

**Comment by BruceKendall** [comment]
The challenge is that encoding information is not saved with csv files, and Excel by default strips out (or replaces with gibberish) all non-ascii characters when reading in the csv file.

The help page for `write.csv` has this to say:
> CSV files do not record an encoding, and this causes problems if they are not ASCII for many other applications. Windows Excel 2007/10 will open files (e.g., by the file association mechanism) correctly if they are ASCII or UTF-16 (use fileEncoding = "UTF-16LE") or perhaps in the current Windows codepage (e.g., "CP1252"), but the ‘Text Import Wizard’ (from the ‘Data’ tab) allows far more choice of encodings. Excel:mac 2004/8 can import only ‘Macintosh’ (which seems to mean Mac Roman), ‘Windows’ (perhaps Latin-1) and ‘PC-8’ files. OpenOffice 3.x asks for the character set when opening the file.

The suggestion to use UTF-16LE renders the csv file human-unreadable, and does not solve the problem, at least for Excel 16.2 on Mac. Instead, save the csv file using UTF-8, and use the Import dialog in Excel (instead of just opening the file), where one can set the encoding.

**Comment by BruceKendall** [comment]
I also note that, having imported the data as UTF-8, Excel then has the option to save the file as a UTF-8 encoded csv file. Thank goodness for sensible programming!
